source "https://rubygems.org"

gem "activerecord", :require => "active_record"
gem "bcrypt"
gem "pry"
gem 'rack-flash3', :require => "rack-flash"
gem "rake"
gem "require_all"
gem "shotgun"
gem "sinatra"
gem "sinatra-activerecord", :require => "sinatra/activerecord"
gem "sqlite3"
